from classes.fase import Fase
from constantes import *

# A matriz do layout define a estrutura do nível
LAYOUT = [
'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADAAAGAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAADADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADAAAAAAAAAAAAAAAAW',
'WWWWWWWWWWAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'WAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAWAAAADADAAAAAAADADAAAAAAADADAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAGAAAAAAAAAWAAAADADAAAAAAADADAAAAAAADADAAAAAAAAAAAAAAAAAW',
'WWWWWWWWWWAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAADDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAPAAAAAADAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAADDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAW',
'WWWWWWWWWWWWWWWWWWWWW             WWWWWWWWWWWWWWWWWWWWWWWWWW',
'T                                                          T',
'T                                                          T',
'T                                                          T',
'T                                                          T',
'T                                                          T',
'T        J                                                 T',
'T                                                          T',
'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
]
TILE_SIZE = 64


class Fase1(Fase):
    def __init__(self, screen, player):
        # 1. Inicializa a classe Fase base
        super().__init__(screen, player)

        # 2. Chama o método para construir o nível usando o layout e o tamanho do tile
        self.create_level(LAYOUT, TILE_SIZE)